---
- name: Example playbook using AWS EC2 plugin
  hosts: localhost
  tasks:
    - name: Configure AWS EC2 inventory plugin
      ansible.builtin.debug:
        msg: "AWS EC2 inventory plugin configured"
      vars:
        plugin: aws_ec2
        regions:
          - us-east-1
        aws_access_key: 123
        aws_secret_key: 123
        keyed_groups:
          - key: tags
            prefix: tag
          - prefix: instance_type
          - key: placement.region
            prefix: aws_region
        filters:
          instance-state-name: running
        compose:
          ansible_host: public_ip_address