---
- hosts: all
  become: true
  vars_prompt:
    - name: wp_db_name
      prompt: Enter the WordPress database name
      private: no

    - name: wp_db_user
      prompt: Enter the WordPress database username
      private: no

    - name: wp_db_password
      prompt: Enter the WordPress database password
      private: yes

  vars:
    db_host: db
    wp_name: wordpress
    docker_network: wordpress_net
    wp_container_port: 80

  tasks:
    - name: Create Docker network
      docker_network:
        name: wordpress_net
        state: present

    - name: Pull WordPress image
      docker_image:
        name: wordpress
        source: pull

    - name: Pull MySQL image
      docker_image:
        name: mysql:5.7
        source: pull

    - name: Deploy MySQL container
      docker_container:
        name: mysql
        image: mysql:5.7
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "{{ wp_db_password }}"
          MYSQL_DATABASE: "{{ wp_db_name }}"
          MYSQL_USER: "{{ wp_db_user }}"
          MYSQL_PASSWORD: "{{ wp_db_password }}"
        networks:
          - name: wordpress_net

    - name: Deploy WordPress container
      docker_container:
        name: wordpress
        image: wordpress:latest
        state: started
        ports:
          - "8080:80"
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: "{{ wp_db_user }}"
          WORDPRESS_DB_PASSWORD: "{{ wp_db_password }}"
          WORDPRESS_DB_NAME: "{{ wp_db_name }}"
        networks:
          - name: wordpress_net
